version: "3.9"

networks:
  msnet:

volumes:
  sql_data:

services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "8085:80"
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [msnet]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks: [msnet]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_password123' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [msnet]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10

  iam:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
    command: >
      dotnet watch run --project src/Services/Iam/Iam/Iam.csproj --urls http://0.0.0.0:80
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=IamDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.http.routers.iam.rule=PathPrefix(`/iam`)"
      - "traefik.http.services.iam.loadbalancer.server.port=80"
    networks: [msnet]

  expedientes:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
    command: >
      dotnet watch run --project src/Services/Expedientes/Expedientes/Expedientes.csproj --urls http://0.0.0.0:80
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=ExpedientesDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.http.routers.expedientes.rule=PathPrefix(`/expedientes`)"
      - "traefik.http.services.expedientes.loadbalancer.server.port=80"
    networks: [msnet]
